---
- name: stat | atomic
  stat:
    path: /opt/Atomic-Toolkit
  register: atomic

- name: pre | grab atomic
  git:
    repo: https://github.com/htpcBeginner/AtoMiC-ToolKit
    dest: /opt/AtoMiC-ToolKit
  when: ( atomic.stat.exists == False )

- name: vpn | install vpn
  apt:
    deb: "https://download.expressvpn.xyz/clients/linux/{{ vpn_deb }}"

- name: stat | vpncheck
  stat:
    path: /usr/local/bin/checker
  register: vpncheck

- name: extra | vpncheck
  copy:
    src: checker
    dest: /usr/local/bin/checker
    owner: root
    group: root
    mode: 0755
  when: ( vpncheck.stat.exists == False )

- name: stat | cron
  stat:
    path: /etc/cron.d/vpncheck
  register: cron

  #- name: extra | cron
  #copy:
    #src: cronfile
    #dest: /etc/cron.d/vpncheck
    #owner: root
    #group: root
    #mode: 0644
    #  when: ( cron.stat.exists == False )
