---
- name: stat | atomic
  stat:
    path: /opt/Atomic-Toolkit
  register: atomic

- name: pre | grab atomic
  git:
    repo: https://github.com/htpcBeginner/AtoMiC-ToolKit
    dest: /opt/AtoMiC-ToolKit
  when: ( atomic.stat.exists == False )

- name: vpn | install vpn
  apt:
    deb: "https://download.expressvpn.xyz/clients/linux/{{ vpn_deb }}"
