---
- name: Install deps
  package: name=nodejs state=installed

- name: Install forever (to run Node.js app)
  npm: name=forever global=yes state=latest

- name: Check list of Node.js apps running
  command: forever list
  register: forever_list
  changed_when: false
