---
- name: Install deps
  package: name={{ item }} state=installed
  with_items:
    - nodejs
    - clang
    - clang-devel
    - gcc

- name: Create drinkbot dir
  file:
    path={{ drinkbot_dir }}
    state=directory
    owner={{ usernm }}
    group={{ usernm }}
    mode=0755

- name: Grab drinkbot from git
  git:
    repo=https://github.com/bechurch/DrinkBot.git
    dest="{{ drinkbot_dir }}"
    update=no
    accept_hostkey=yes
  register: drinkbot_git

- name: Install forever (to run Node.js app)
  npm: name=forever global=yes state=latest
