---
mysql_packages:
  - mariadb-server
  - mariadb-client
  - python-mysqldb

nginx_packages:
  - nginx-full
  - php7.0-cli
  - php7.0-curl
  - php7.0-fpm
  - php7.0-gd
  - php7.0-json
  - php7.0-mcrypt
  - php7.0-mysql
  - php7.0-snmp
  - php-net-ipv4
  - php-net-ipv6
  - php-pear

tools_packages:
  - fping
  - git
  - graphviz
  - imagemagick
  - mtr-tiny
  - nmap
  - rrdtool
  - snmp
  - snmpd
  - whois
