---
- block:
    - name: add libselinux-python for selinux
      package:
        name: libselinux-python
        state: present

    - name: disable selinux
      selinux:
        state: disabled

  when: ansible_distribution == 'CentOS'
  rescue:
    - debug: msg='this is meant for CentOS only'
