---
- name: add sudo
  package : name=sudo state=present

- name: Add custom sudoers
  copy: src=soehlert dest=/etc/sudoers.d/soehlert owner=root group=root mode=0440 validate='/usr/sbin/visudo -cf %s'
