---
- name: packages | add epel if centos
  package:
    name: epel-release
    state: present
  when: ansible_distribution == "CentOS"

- name: packages | add default packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ defaults }}"

- name: packages | add pip packages
  pip:
    name: "{{ item }}"
  when: "'media' in group_names"
  with_items:
    - "{{ pip_media }}"
