---
- name: add vim
  package : name=vim state=present

- name: add wget
  package : name=wget state=present

- name: add libselinux-python for selinux
  package : name=libselinux-python state=present
