---
- name: add default packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ defaults }}"

- name: need pandoc for soundscrape
  package:
    name: pandoc
    state: present

- name: add media packages
  pip:
    name: "{{ item }}"
  when: "'media' in group_names"
  with_items:
    - "{{ pip_media }}"
