---
- name: packages | add epel if centos
  package:
    name: epel-release
    state: present
  when: ansible_os_family == "RedHat"

- name: packages | add default packages
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - "{{ default_packages }}"
