---
# tasks file for roles/plexupdate
- name: Create plexupdate directory layout
  file:
    name: "{{ plexupdate_dir }}/{{ item }}"
    state: directory
  loop:
    - etc
    - bin

- name: Clone plexupdate
  git:
    repo: "{{ plexupdate_repo }}"
    dest: "{{ plexupdate_dir }}/bin"
    version: master

- name: Install plexupdate cron conf
  template:
    src: plexupdatecron.conf.j2
    dest: /etc/plexupdate.cron.conf
    owner: root
    group: root
    mode: 0644

- name: Create plexupdate cron job
  file:
    src: "{{ plexupdate_dir }}/bin/extras/cronwrapper"
    dest: /etc/cron.daily/plexupdate
    owner: root
    group: root
    state: link

- name: Create plexupdate conf file
  template:
    src: plexupdate.conf.j2
    dest: "{{ plexupdate_dir }}/etc/plexupdate.conf"
    owner: root
    group: root
    mode: 0644
