---
# tasks file for roles/proxmox
- name: Remove enterprise repo
  file:
      path: /etc/apt/sources.list.d/pve-enterprise.list
      state: absent

- name: Install no subscription repo file
  template:
      src: proxmox.repo.j2
      dest: /etc/apt.sources.list.d/pve-no-sub.repo
      owner: root
      group: root
      mode: 0644

- name: Install proxmox prereqs
  pip:
    name: "{{ item }}"
    extra_args: --user
  with_items:
      - proxmoxer
      - requests

- name: Remove the license warning
  lininefile:
      path: '/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js'
      regexp: 'data.status !== Active'
      line: 'data.status !== false'

- name: Download templates
  delegate_to: proxmox
  command: "/usr/bin/pveam donload local {{ item }}"
  args:
      creates: "/var/lib/vz/template/cache/{{ item }}"
  with_items:
      - "{{ container_templates }}"

- name: Install proxmox containers with mounts
  proxmox:
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    password: "{{ promox_root_password }}"
    hostname: "{{ item.hostname }}"
    ostemplate: "{{ item.ostemplate }}"
    netif: "{{ item.netif }}"
    mounts: "{{ item.mount|default(omit) }}"
  with_items: "{{ proxmox_containers }}"

- name: Start containers
  proxmox:
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    state: started
    hostname: "{{ item.hostname }}"
  retries: 10
  delay: 2
  ignore_errors: yes
  with_items: "{{ proxmox_containers }}"
