---
- name: Trust Proxmox' packaging key
  apt_key:
    data: "{{ lookup('file', pve_release_key) }}"
    id: "{{ pve_release_key_id }}"
    state: present

- name: Remove Enterprise repo
  apt_repository:
    repo: deb https://enterprise.proxmox.com/debian jessie pve-enterprise
    state: absent
    filename: pve-enterprise

- name: Enable proxmox no-subscription repo
  apt_repository:
    repo: deb http://download.proxmox.com/debian jessie pve-no-subscription
    state: present
    filename: pve-no-subscription

- name: Update apt cache
  apt:
    update_cache: true

- name: Install dab and prereqs
  apt:
    pkg:
      - dab
      - git
      - make
      - python-pip
    state: present
    update_cache: true

- name: Clone my dab repo
  git:
    repo: "{{ dab_repo }}"
    dest: /opt/dab_templates
    accept_hostkey: true
  when: dab_repo is defined

- name: Install proxmox prereqs
  pip:
    name: 
      - proxmoxer
      - requests
    extra_args: --user

- name: Remove the license warning
  replace:
    path: '/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js'
    regexp: "data.status !== 'Active'"
    replace: "false"

- name: Download templates
  delegate_to: "{{ inventory_hostname }}"
  command: "/usr/bin/pveam download local {{ item }}"
  args:
    creates: "/var/lib/vz/template/cache/{{ item }}"
  with_items:
    - "{{ container_templates }}"
