---
- hosts: all
  user: soehlert
  become: true
  become_user: root
  roles:
    - users
    - packages
    - { role: iptables, when: "ansible_os_family == 'Debian'" }
    - { role: firewalld, when: "ansible_os_family == 'RedHat'" }
