---
- name: Install Deps
  package: name={{ item }} state=present
  with_items:
    - nodejs
    - npm
    - redis

- name: Create Hoddlebot directory
  file:
    path={{ hoddlebot_path }}
    state=directory
    owner={{ usernm }}
    group={{ usernm }}
    mode=0755

- name: Install hubot
  npm: name={{ item }} global=yes
  with_items:
    - yo
    - generator-hubot
    - hubot
    - coffee-script

- name: Create my hoddlebot
  become: true
  become_user: soehlert
  shell: cd {{hoddlebot_path }}; yo hubot --owner={{ hoddlebot_owner }} --name={{ hoddlebot_name }} --description={{ hoddlebot_description }} --adapter={{ hoddlebot_adapter }} --defaults
    creates={{ hoddlebot_path}}/bin/hubot

- name: Install hoddlebot script
  template:
    src=/mytemplates/hoddlebot.sh.j2
    dest={{ hoddlebot_path }}/bin/hoddlebot.sh
    owner={{ usernm }}
    group={{ usernm }}
    mode=0755
