---
# tasks file for roles/beets
- include_vars: vault.yml

- name: Install beets
  pip:
    name: beets

- name: Install some beets plugins prereqs
  pip:
    name: "{{ item }}"
  loop: "{{ beets_plugin_prereqs }}"

- name: Install gstreamer for beets
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ beets_gstreamer }}"

- name: Create etc dirs
  file:
    path: "{{ beets_dir }}/etc"
    state: directory
    owner: "{{ usernm }}"
    group: users

- name: Copy beets config
  template:
    src: config.yaml.j2
    dest: "{{ beets_dir }}/etc/config.yml"
    owner: "{{ usernm }}"
    group: users
