---
# tasks file for roles/cloudflare-ddns
- name: Install pip3
  package:
    name: python3-pip
    state: present

- name: Install requests
  pip:
    name: requests
    state: present
    executable: pip3

- name: Create {{ cf_ddns_user }} user
  user:
    name: "{{ cf_ddns_user }}"
    comment: "Cloudflare DDNS"
    create_home: false
    password_lock: true
    system: true

- name: Check for clone at {{ cf_ddns_path }}
  stat:
    path: "{{ cf_ddns_path }}"
  register: clone

- name: Create clone directory at {{ cf_ddns_path }}
  file:
    path: "{{ cf_ddns_path }}"
    state: directory
    owner: "{{ cf_ddns_user }}"
    group: "{{ cf_ddns_user }}"
  when: not clone.stat.exists

- name: Clone repo from {{ cf_ddns_repo }}
  git:
    repo: "{{ cf_ddns_repo }}"
    dest: "{{ cf_ddns_path }}"
    accept_hostkey: true
  when: clone.stat.exists

- name: Create config file in {{ cf_ddns_path }}
  template:
    src: config.json.j2
    dest: "{{ cf_ddns_path }}/config.json"
    owner: "{{ cf_ddns_user }}"
    group: "{{ cf_ddns_user }}"

- name: Create systemd files to run this
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    owner: root
    group: root
  loop:
    - cf_ddns.service
    - cf_ddns.timer

- name: Reload systemd
  systemd:
    daemon_reload: true
  notify: Start_cf_ddns

- name: Enable service and timer
  systemd:
    name: "{{ item }}"
    enabled: true
  loop:
    - cf_ddns.service
    - cf_ddns.timer
