---
# tasks file for roles/updates
- name: Update debian
  apt:
    name: '*'
    state: latest
    update_cache: yes
  run_once: true
  notify: reboot
  when: ansible_os_family == "Debian"

- name: Update RHEL
  yum:
    name: '*'
    state: latest
  run_once: true
  notify: reboot
  when: ansible_os_family == "RHEL"
