---
# tasks file for roles/smokeping
- name: Update cache
  apt:
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install smokeping
  package:
    name: smokeping
    state: present

- name: Install configs
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 644
  notify: restart apache
  with_items:
    - { src: 'templates/smokeping.conf.j2', dest: '/etc/smokeping/config.d/General' }
    - { src: 'templates/pathnames.conf.j2', dest: '/etc/smokeping/config.d/pathnames' }
    - { src: 'templates/alerts.conf.j2', dest: '/etc/smokeping/config.d/Alerts' }
    - { src: 'templates/targets.conf.j2', dest: '/etc/smokeping/config.d/Targets' }
    - { src: 'templates/smokeping.cgi.j2', dest: '/etc/apache2/conf-available/serve-cgi-bin.conf' }

- name: Create links
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items:
    - { src: '/usr/share/smokeping/www', dest: '/var/www/smokeping' }
    - { src: '/usr/lib/cgi-bin/smokeping.cgi', dest: '/usr/share/smokeping/www/smokeping.cgi' }

- name: Check if CGI is enabled
  stat:
    path: /etc/apache2/mods-enabled/cgid.load
  register: cgi

- name: Enable CGI
  apache2_module:
    name: cgi
    state: present
  when: cgi.stat.exists == False
  notify: restart apache
