---
# handlers file for roles/updates
- name: Reboot
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  notify: Wait for server

- name: Wait for server
  local_action: wait_for host="{{ inventory_hostname }}" state=started port=22
