---
# handlers file for roles/containers
# Can't start containers when creating them as it
# tries to start it before it creates the container
- name: start_containers
  proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_root_password }}"
    hostname: "{{ item.hostname }}"
    state: started
  retries: 10
  delay: 2
  with_items: "{{ proxmox_containers }}"
