---
# tasks file for roles/containers
- name: Install proxmox containers
  proxmox:
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    password: "{{ proxmox_root_password }}"
    hostname: "{{ item.hostname }}"
    onboot: "{{ item.onboot|default('true')}}"
    ostemplate: "{{ item.ostemplate }}"
    cores: "{{ item.cores|default(2)}}"
    cpus: "{{ item.cpus|default(1)}}"
    cpuunits: "{{ item.cpuunits|default(2400)}}"
    disk: "{{ item.disk|default(20)}}"
    ip_address: "{{ item.ip_address|default(omit) }}"
    memory: "{{ item.memory|default(2048)}}"
    mounts: "{{ item.mounts|default(omit) }}"
    netif: "{{ item.netif|default(omit) }}"
    storage: "{{ item.storage }}"
    vmid: "{{ item.vmid|default(omit) }}"
  with_items: "{{ proxmox_containers }}"

# Can't start containers when creating them as it
# tries to start it before it creates the container
- name: start_containers
  proxmox:
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_root_password }}"
    hostname: "{{ item.hostname }}"
    state: started
  retries: 10
  delay: 2
  with_items: "{{ proxmox_containers }}"
