---
# tasks file for roles/containers
- name: Install proxmox containers
  proxmox:
    node: "{{ proxmox_node }}"
    api_host: "{{ proxmox_api_host }}"
    api_user: "{{ proxmox_user }}"
    api_password: "{{ proxmox_password }}"
    password: "{{ proxmox_root_password }}"
    hostname: "{{ item.hostname }}"
    onboot: "{{ item.onboot|default('true')}}"
    ostemplate: "{{ item.ostemplate }}"
    cores: "{{ item.cores|default(omit)}}"
    cpus: "{{ item.cpus|default(omit)}}"
    disk: "{{ item.disk|default(omit)}}"
    ip_address: "{{ item.ip_address|default(omit) }}"
    memory: "{{ item.memory|default(omit)}}"
    mounts: "{{ item.mounts|default(omit) }}"
    netif: "{{ item.netif|default(omit) }}"
    storage: "{{ item.storage }}"
    vmid: "{{ item.vmid|default(omit) }}"
  with_items: "{{ proxmox_containers }}"
  notify: start_containers
