---
- name: Clone specified NetBox git repository
  git:
    repo: "{{ netbox_git_uri }}"
    dest: "{{ netbox_git_repo_path }}"
    version: "{{ netbox_git_version }}"
  register: __netbox_git_repo
  become: True
  become_user: "{{ netbox_user }}"

- name: Create git deployment directory for NetBox
  file:
    path: "{{ netbox_git_deploy_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    state: directory

- name: Check existence of commit 643f64d, affecting MEDIA_ROOT
  shell: 'git log --format=%H "{{ netbox_git_version }}" | grep ^643f64df3f02912957c2faf1a7555876fe00e2bc'
  args:
    chdir: "{{ netbox_git_repo_path }}"
  register: __netbox_git_contains_media_root_change
  changed_when: False
  failed_when: "__netbox_git_contains_media_root_change.rc not in [0, 1]"

- name: Ensure MEDIA_ROOT is defined if commit 643f64d exists
  fail:
    msg: "Please define MEDIA_ROOT in netbox_config."
  when:
    - __netbox_git_contains_media_root_change.rc == 0 and "MEDIA_ROOT" not in netbox_config

- name: Check existence of commit 97188ad, fixing issue netbox#1563
  shell: 'git log --format=%H "{{ netbox_git_version }}" | grep ^97188ad85ba77d361ae38d8b5e01ae9109e5e9bd'
  args:
    chdir: "{{ netbox_git_repo_path }}"
  register: __netbox_git_contains_issue_1563_fix
  changed_when: False
  failed_when: "__netbox_git_contains_issue_1563_fix.rc not in [0, 1]"

- name: Archive and extract snapshot of git repository
  shell: 'git archive "{{ netbox_git_version }}" | tar -x -C "{{ netbox_git_deploy_path }}"'
  args:
    chdir: "{{ netbox_git_repo_path }}"
  notify:
    - reload netbox.service
  when:
    - __netbox_git_repo | changed
  become: True
  become_user: "{{ netbox_user }}"

- name: Symlink git repository to current NetBox directory
  file:
    src: "{{ netbox_git_deploy_path }}"
    dest: "{{ netbox_current_path }}"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    state: link
