---
# tasks file for lae.netbox
- include: validate_variables.yml

- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

- include: "install_packages_{{ ansible_pkg_mgr }}.yml"

- name: Install virtualenv via pip
  pip:
    name: virtualenv
    state: latest
    executable: "{{ netbox_pip3_binary if (netbox_python == 3) else netbox_pip2_binary }}"

- name: Create NetBox user group
  group:
    name: "{{ netbox_group }}"

- name: Create NetBox user and home directory
  user:
    name: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    home: "{{ netbox_home }}"

- name: Ensure Postgres database exists (via socket)
  postgresql_db:
    name: "{{ netbox_database }}"
    login_user: "{{ netbox_database_user }}"
    login_unix_socket: "{{ netbox_database_socket }}"
  become: True
  become_user: "{{ netbox_database_user }}"
  when:
    - netbox_database_socket is defined
    - netbox_database_host is not defined

- name: Ensure Postgres database exists (via TCP)
  postgresql_db:
    name: "{{ netbox_database }}"
    login_host: "{{ netbox_database_host }}"
    port: "{{ netbox_database_port }}"
    login_user: "{{ netbox_database_user }}"
    login_password: "{{ netbox_database_password }}"
  when:
    - netbox_database_socket is not defined
    - netbox_database_host is defined

- include: deploy_netbox.yml

- name: Install uWSGI via pip
  pip:
    name: uwsgi
    state: latest
    executable: "{{ netbox_pip3_binary if (netbox_python == 3) else netbox_pip2_binary }}"
  notify:
    - reload netbox.service

- name: Configure uWSGI NetBox application
  template:
    src: uwsgi.ini.j2
    dest: "{{ netbox_shared_path }}/uwsgi.ini"
    owner: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
  notify:
    - reload netbox.service

- name: Install NetBox socket unit file
  template:
    src: netbox.socket.j2
    dest: /lib/systemd/system/netbox.socket
  notify:
    - restart netbox.socket

- name: Install NetBox service unit file
  template:
    src: netbox.service.j2
    dest: /lib/systemd/system/netbox.service
  notify:
    - restart netbox.service

- name: Start and enable NetBox' socket/service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - netbox.socket
    - netbox.service
