---
# tasks file for roles/jackett
- block:
  - name: Install prereqs
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - libcurl4-openssl-dev
      - bzip2

  - name: Register Jackett version
    shell: wget -q https://github.com/Jackett/Jackett/releases/latest -O - | grep -E \/tag\/ | awk -F "[><]" '{print $3}'
    register: jackett_version

  - name: Grab and untar Jackett
    unarchive:
      src: "https://github.com/Jackett/Jackett/releases/download/{{ jackett_version.stdout }}/Jackett.Binaries.Mono.tar.gz"
      dest: /tmp/
      remote_src: True

  - name: Create Jackett directory
    file:
      state: directory
      path: /opt/jackett
      owner: "{{ jackett_user }}"
      group: "{{ jackett_group }}"

  - name: Move Jackett files to correct directory
    shell: mv /tmp/Jackett/* /opt/jackett

  - name: Add systemd file
    template:
      src: templates/jackett.service.j2
      dest: /etc/systemd/system/jackett.service
      mode: 0755
      owner: root
      group: root

  - name: Enable and start service
    systemd:
      name: jackett
      daemon_reload: yes
      enabled: True
      state: started

- rescue:
  - debug: msg='This is meant for Debian based systems'
