---
- name: Make sure projects dir exists
  file:
    path: "{{ rancid_path }}"
    owner: "{{ usernm }}"
    group: "{{ usernm }}"
    state: directory
    mode: 0775

- name: Install build deps
  package:
    name: "{{ item }}"
    state: present
  become: true
  become_user: root
  with_items:
    - gcc
    - expect
    - automake
    - perl
    - autoconf
    - m4

- name: Grab rancid-git from git
  git:
    repo: https://github.com/dotwaffle/rancid-git.git
    dest: "{{ rancid_git_path }}"
    update: no
    accept_hostkey: yes
  register: rancid_git

- block
    - name: Dirty hack, but need to avoid aclocal errors
      shell: autoreconf -fi
      args:
        chdir: "{{ rancid_git_path }}"

    - name: Build rancid-git
      shell: "{{ item }}"
      args:
        chdir: "{{ rancid_git_path }}"
      with_items:
        - ./configure --prefix: {{ rancid_path}} --localstatedir: {{ rancid_path }}/var/rancid
        - make install
  
  when: rancid_git.changed

  rescue:
     - debug: msg='This failed in the section that only appears when downloading a new version of rancid-git'

- name: Install conf file
  copy:
    src: rancid.conf
    dest: {{ rancid_path }}/etc/rancid.conf
    owner: "{{ usernm }}"
    group: "{{ usernm }}"
    mode: 0644

- name: Add cloginrc file
  template:
    src: cloginrc
    dest: /home/{{ usernm }}/.cloginrc
    owner: "{{ usernm }}"
    group: "{{ usernm }}"
    mode: 0600
