---
# tasks file for lockdown
- name: Make SURE another user and key exists
  stat:
    path: "/home/{{ item.user }}/.ssh/authorized_keys"
  when: "{{ create_users }}"
  with_items:
    - "{{ create_users }}"
  register: user_exists

- name: Make sure user has sudo or we're stuck without root
  stat:
    path: "/etc/sudoers.d/{{ item.user }}"
  when: "{{ create_users }}"
  with_items:
    - "{{ create_users }}"
  register: sudo_access

- name: Cut off remote root ssh
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  when: user_exists and sudo_access
  with_items:
    - { regexp: '^PasswordAuthentication', line: 'PasswordAuthentication no' }
    - { regexp: '^PermitRootLogin', line: 'PermitRootLogin no' }
  notify: restart_sshd

- name: Update all packages
  yum:
    name: *
    state: latest
    update_cache: yes    
  when: ansible_os_family = "RedHat"

- name: Update all packages deb
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
