---
- name: Install mariadb
  package:
    name: mariadb-server
    state: present

- name: Enable and start httpd and mariadb
  service:
    name: mariadb
    enabled: yes
    state: started

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: copy .my.cnf file with root password credentials
  template:
    src: my.cnf.j2
    dest: /root/my.cnf
    owner: root
    mode: 0600

- name: delete anonymous MySQL server user for hostname
  mysql_user:
    name: ''
    host_all: yes
    state: absent

- name: delete anonymous MySQL server user for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent

- name: remove the MySQL test database
  mysql_db:
    name: test
    state: absent
