---
iptables_chains:
  - name: 'INPUT'
    rules:
      - comment: 'Allow HTTP'
        ctstate: 'NEW'
        jump: 'ACCEPT'
        state: 'present'
        table: 'filter'
        destination_port: '8085'
        protocol: 'tcp'
      - comment: 'Allow couchpotato'
        ctstate: 'NEW'
        jump: 'ACCEPT'
        state: 'present'
        table: 'filter'
        destination_port: '5050'
        protocol: 'tcp'
      - comment: 'Allow deluge web'
        ctstate: 'NEW'
        jump: 'ACCEPT'
        state: 'present'
        table: 'filter'
        destination_port: '8112'
        protocol: 'tcp'
      - comment: 'Allow headphones'
        ctstate: 'NEW'
        jump: 'ACCEPT'
        state: 'present'
        table: 'filter'
        destination_port: '8181'
        protocol: 'tcp'
      - comment: 'Allow sonarr'
        ctstate: 'NEW'
        jump: 'ACCEPT'
        state: 'present'
        table: 'filter'
        destination_port: '8989'
        protocol: 'tcp'
      - comment: 'Allow transmission'
        ctstate: 'NEW'
        jump: 'ACCEPT'
        state: 'present'
        table: 'filter'
        destination_port: '9091'
        protocol: 'tcp'
