---
- name: Install NFS client
  package:
    name: nfs-utils
    state: present
  tags:
    - install
  when: ansible_distribution == 'CentOS'

- name: Install NFS client
  package:
    name: nfs-common
    state: present
  tags:
    - install
  when: ansible_distribution == 'Ubuntu'

- name: Turn on NFS client
  service:
    name: rpcbind
    state: started
    enabled: yes
  tags:
    - install

- name: Ensure mount dir exists
  file:
    path: "{{ item.nfs_mount }}"
    state: directory
  with_items: "{{ nfs_client }}"
  tags:
    - directory

- name: Make the mount
  mount:
    name: "{{ item.nfs_mount }}"
    src: "{{ item.nfs_server }}:/{{ item.nfs_dir }}"
    fstype: nfs
    state: mounted
    opts: "{{ item.nfs_options }}"
  with_items: "{{ nfs_client }}"
  tags:
    - mount
