---
# tasks file for roles/plex
- name: Add stuff for https repo
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates

- name: Accept key
  apt_key:
    url: https://downloads.plex.tv/plex-keys/PlexSign.key
    state: present

- name: Add apt repo
  apt_repository:
    repo: deb https://downloads.plex.tv/repo/deb/ public main
    state: present
    filename: 'plex'

- name: Update apt cache
  apt:
    update_cache: true

- name: Install prereqs
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - avahi-daemon
    - avahi-utils
    - cifs-utils
    - git
    - libavahi-client3
    - libavahi-common3
    - libavahi-core7
    - libdaemon0
    - libnss-mdns

- name: Install plex
  package:
    name: plexmediaserver
    state: present

- name: Daemon reload
  systemd:
    daemon_reload: true

- name: Start plex
  systemd:
    name: plexmediaserver
    state: started
    enabled: true
