---
- hosts: all
  user: "{{ usernm }}"
  become: true
  become_user: root
  roles:
    - { role: "users", tags: "users" }
    - { role: "packages", tags: "packages" }
  #    - { role: iptables, when: "ansible_os_family == 'Debian'" }
  #  - { role: firewalld, when: "ansible_os_family == 'RedHat'" }
