---
- hosts: all
  user: vagrant
  become: true
  become_user: root
  roles:
    - { role: 'users', tags: 'users' }
    - { role: 'packages', tags: 'packages' }
    - { role: 'iptables', tags: 'iptables', when: "ansible_os_family == 'Debian'" }
    - { role: 'firewalld', tags: 'firewalld', when: "ansible_os_family == 'RedHat'" }
