---
- hosts: private
  user: soehlert
  become: true
  become_user: root
  roles:
    - groups
    - user
    - sources
    - sudoers

- hosts: centos
  user: soehlert
  become: true
  become_user: root
  roles:
      - selinux

- hosts: private
  user: soehlert
  become: true
  become_user: root
  roles:
    - packages
    - git

- hosts: centos7
  user: soehlert
  become: true
  become_user: root
  roles:
    - firewalld

- hosts: localhost
  user: soehlert
  become: true
  become_user: root
  roles:
    - groups
    - sudoers
    - packages
    - firewalld
