---
- hosts: all
  user: "{{ usernm }}"
  become: true
  become_user: root
  pre_tasks:
    - name: 'install python2'
      raw: sudo apt-get -y install python-simplejson
  roles:
    - { role: 'packages', tags: 'packages' }
    - { role: 'users', tags: 'users' }
