---
- hosts: private
  user: root
  roles:
    - groups
    - user
    - sudoers

- hosts: private
  user: soehlert
  sudo: true
  sudo_user: root
  roles:
    - packages
    - git
    - firewalld

- hosts: localhost
  user: soehlert
  sudo: true
  sudo_user: root
  roles:
    - groups
    - sudoers
    - packages
    - firewalld
