---
- hosts: private
  user: soehlert
  become: true
  become_user: root
  roles:
    - groups
    - user

- hosts: centos
  user: soehlert
  become: true
  become_user: root
  roles:
      - selinux

- hosts: private
  user: soehlert
  become: true
  become_user: root
  roles:
    - packages
    - git
    - sudoers

- hosts: centos7
  user: soehlert
  become: true
  become_user: root
  roles:
    - firewalld

- hosts: debian
  user: deploy
  become: true
  become_user: root
  roles:
    - sources

- hosts: localhost
  user: soehlert
  become: true
  become_user: root
  roles:
    - groups
    - sudoers
    - packages
    - firewalld
