---
- hosts: private
  user: deploy
  sudo: true
  sudo_user: root
  roles:
    - groups
    - user
    - sudoers
    - packages
    - firewalld

- hosts: localhost
  user: soehlert
  sudo: true
  sudo_user: root
  roles:
    - groups
    - sudoers
    - packages
    - firewalld
