---
- hosts: all
  user: soehlert
  become: true
  become_user: root
  roles:
    - { role: 'packages', tags: 'packages' }
    - { role: 'netdata', tags: 'netdata' }
    - { role: 'auto-updates', tags: 'auto-updates' }
