---
- hosts: private
  user: "{{ usernm }}"
  become: true
  become_user: root
  roles:
    - groups
    - user
    - packages
    - git
    - vmwaretools

- hosts: centos
  user: "{{ usernm }}"
  become: true
  become_user: root
  roles:
    - selinux

- hosts: private
  user: "{{ usernm }}"
  become: true
  become_user: root
  roles:
    - sudoers
