---
- hosts: all
  user: vagrant
  become: true
  become_user: root
  roles:
    - { role: 'packages', tags: 'packages' }
    - { role: 'users', tags: 'users' }
    - { role: 'netdata', tags: 'netdata' }
