---
- hosts: ipam
  become: true
  roles:
    - geerlingguy.postgresql
    - lae.netbox
  vars:
    netbox_stable: true
    netbox_socket: "0.0.0.0:80"
    netbox_superuser_password: netbox
    netbox_config:
      ALLOWED_HOSTS:
        - "*"
      MEDIA_ROOT: "{{ netbox_shared_path }}/media"
      REPORTS_ROOT: "{{ netbox_shared_path }}/reports"
    netbox_database_socket: "{{ postgresql_unix_socket_directories[0] }}"
    postgresql_users:
      - name: "{{ netbox_database_user }}"
        role_attr_flags: CREATEDB,NOSUPERUSER
