---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install local prereqs
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - proxmoxer
        - requests

- hosts: proxmox
  roles:
    - { role: 'proxmox', tags: 'proxmox' }
