---
- name: maas | add apt-repository
  apt_repository:
    repo: 'ppa:maas/stable'

- name: maas | install maas
  package:
    name: maas
    state: present

- name: maas | next steps
  debug:
    msg: "Now run: sudo maas-region-admin createadmin then go to web interface at http://<your.maas.ip>:5240/MAAS/"
