---
- name: Install prereqs
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - fping
    - git
    - graphviz
    - imagemagick
    - mariadb-client
    - mariadb-server
    - mtr-tiny
    - nginx-full
    - nmap
    - php7.0-cli
    - php7.0-curl
    - php7.0-fpm
    - php7.0-gd
    - php7.0-json
    - php7.0-mcrypt
    - php7.0-mysql
    - php7.0-snmp
    - php-net-ipv4
    - php-net-ipv6
    - php-pear
    - python-mysqldb
    - rrdtool
    - snmp
    - snmpd
    - whois

- name: Create DB
  mysql_db:
    name: librenms
    state: present
  notify: restart_mysql

- name: Create DB User
  mysql_user:
    name: librenms
    host: localhost
    priv: librenms.*:ALL
    password: "{{ librenms_pass }}"
  notify: restart_mysql

- name: Enable mysql
  service:
    name: mysql
    enabled: yes

- name: Add group
  group:
    name: librenms
    system: True
    state: present

- name: Add user
  user:
    name: librenms
    group: www-data
    comment: 'Librenms'
    system: True
    state: present

- name: Make sure required directories exist
  file:
    dest: '{{ item }}'
    state: 'directory'
    owner: '{{ librenms__user }}'
    group: '{{ librenms__group }}'
    mode: '0750'
  with_items:
    - '{{ librenms__data_path }}'
    - '{{ librenms__rrd_dir }}'
    - '{{ librenms__log_dir }}'



















