---
# handlers file for roles/smokeping
- name: restart apache
  service:
    name: apache2
    state: restarted
  notify: restart smokeping

- name: restart smokeping
  service:
    name: smokeping
    state: restarted
